on: [push]

name: osasere, jeremiah, joshua, ekhator
jobs:

    print_message: 
     runs-on: ubuntu-latest

     steps: 
     - name: print a message
       run: echo "we are students of cenfortech!"